import SwiftUI

/// Renders a markdown string with proper block-level formatting.
///
/// Handles the subset generated by the meeting summary pipeline:
///   # H1, ## H2, ### H3  — headings
///   ---                   — divider
///   - item / * item       — bullet list
///   blank line            — paragraph break
///   inline **bold**, *italic*, `code`  — via AttributedString
struct MarkdownContentView: View {
    let markdown: String

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            ForEach(parse(markdown)) { block in
                blockView(block)
            }
        }
        .textSelection(.enabled)
    }

    // MARK: - Block rendering

    @ViewBuilder
    private func blockView(_ block: Block) -> some View {
        switch block.kind {
        case .h1:
            Text(block.text)
                .font(.title2.bold())
                .foregroundStyle(AppTheme.Colors.primaryText)
                .padding(.top, 20)
                .padding(.bottom, 4)

        case .h2:
            Text(block.text)
                .font(.title3.bold())
                .foregroundStyle(AppTheme.Colors.primaryText)
                .padding(.top, 16)
                .padding(.bottom, 2)

        case .h3:
            Text(block.text)
                .font(.headline)
                .foregroundStyle(AppTheme.Colors.primaryText)
                .padding(.top, 12)
                .padding(.bottom, 2)

        case .hr:
            Divider()
                .padding(.vertical, 12)

        case .bullet(let depth):
            HStack(alignment: .firstTextBaseline, spacing: 8) {
                Text(depth == 0 ? "•" : "◦")
                    .font(AppTheme.Fonts.body)
                    .foregroundStyle(AppTheme.Colors.secondaryText)
                    .frame(width: 12, alignment: .center)
                inlineText(block.text)
                    .font(AppTheme.Fonts.body)
                    .foregroundStyle(AppTheme.Colors.primaryText)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(.leading, CGFloat(depth) * 16)
            .padding(.vertical, 2)

        case .paragraph:
            inlineText(block.text)
                .font(AppTheme.Fonts.body)
                .foregroundStyle(AppTheme.Colors.primaryText)
                .lineSpacing(4)
                .fixedSize(horizontal: false, vertical: true)
                .padding(.top, 6)
        }
    }

    /// Render a string that may contain inline markdown (**bold**, *italic*, `code`).
    private func inlineText(_ text: String) -> Text {
        // SwiftUI Text supports inline markdown via AttributedString.
        if let attr = try? AttributedString(
            markdown: text,
            options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)
        ) {
            return Text(attr)
        }
        return Text(text)
    }

    // MARK: - Parser

    private struct Block: Identifiable {
        enum Kind {
            case h1, h2, h3, hr, paragraph
            case bullet(depth: Int)
        }
        let id = UUID()
        let kind: Kind
        let text: String
    }

    private func parse(_ raw: String) -> [Block] {
        var blocks: [Block] = []
        let lines = raw.components(separatedBy: "\n")
        var i = 0

        while i < lines.count {
            let line = lines[i]
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            i += 1

            if trimmed.isEmpty { continue }

            // Headings
            if trimmed.hasPrefix("### ") {
                blocks.append(Block(kind: .h3, text: String(trimmed.dropFirst(4))))
                continue
            }
            if trimmed.hasPrefix("## ") {
                blocks.append(Block(kind: .h2, text: String(trimmed.dropFirst(3))))
                continue
            }
            if trimmed.hasPrefix("# ") {
                blocks.append(Block(kind: .h1, text: String(trimmed.dropFirst(2))))
                continue
            }

            // Horizontal rule
            if trimmed == "---" || trimmed == "***" || trimmed == "___" {
                blocks.append(Block(kind: .hr, text: ""))
                continue
            }

            // Bullet (unordered list): leading spaces determine depth
            let leadingSpaces = line.prefix(while: { $0 == " " }).count
            let depth = leadingSpaces / 2
            if trimmed.hasPrefix("- ") || trimmed.hasPrefix("* ") {
                let text = String(trimmed.dropFirst(2))
                blocks.append(Block(kind: .bullet(depth: depth), text: text))
                continue
            }

            // Plain paragraph
            blocks.append(Block(kind: .paragraph, text: trimmed))
        }

        return blocks
    }
}
