"""
LLM summarization provider abstraction.

To add a new provider:
1. Subclass SummarizationProvider
2. Implement .summarize()
3. Register it in get_provider()
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass
class SummaryResult:
    # Core fields (all providers, new schema)
    meeting_summary: str = ""
    topics_discussed: list[dict] = field(default_factory=list)   # [{topic, summary, outcome}]
    key_decisions: list[dict] = field(default_factory=list)      # [{decision, rationale, decided_by}]
    action_items: list[dict] = field(default_factory=list)       # [{owner, task, due_date, priority, context}]
    open_questions: list[dict] = field(default_factory=list)     # [{question, raised_by, assigned_to}]
    risks_and_blockers: list[dict] = field(default_factory=list) # [{type, description, severity, mitigation}]
    key_insights: list[str] = field(default_factory=list)
    next_steps_summary: str = ""
    follow_up_email: str = ""
    # Legacy field — kept for backward compat with summaries generated by the old prompt
    risks: list[str] = field(default_factory=list)
    raw_json: dict = field(default_factory=dict)
    markdown: str = ""


class SummarizationProvider(ABC):
    """Base class for all LLM summarization backends."""

    @abstractmethod
    def summarize(self, transcript_text: str, model: str) -> SummaryResult:
        """
        Given a formatted transcript string, produce a structured summary.
        Raises RuntimeError on provider errors.
        """
        ...


def get_provider(name: str) -> SummarizationProvider:
    """Factory — returns provider instance by name."""
    if name == "openai":
        from app.services.summarization.openai_provider import OpenAIProvider
        return OpenAIProvider()
    if name == "ollama":
        from app.services.summarization.ollama_provider import OllamaProvider
        return OllamaProvider()
    if name == "anthropic":
        from app.services.summarization.anthropic_provider import AnthropicProvider
        return AnthropicProvider()
    if name == "gemini":
        from app.services.summarization.gemini_provider import GeminiProvider
        return GeminiProvider()
    raise ValueError(f"Unknown summarization provider: {name!r}")
